
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-image-puller-operator-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    name: kubernetes-image-puller-operator
